name: Amazon Price Tracker

on:
  workflow_dispatch:      # Allows you to click "Run" manually
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 PM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    # Added permissions so the bot can push the 'last_price.txt' back to your repo
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests playwright
          python -m playwright install chromium --with-deps

      - name: Run Scraper
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python scraper.py

      - name: Save Price History
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add price_*.txt # Adds all individual price files
          git commit -m "Update prices for wishlist" || exit 0
          git push
      - name: Upload Debug Screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: error_*.png